//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIS_website.Documents {
    
    
    public partial class ExperienceDoc {
        
        /// <summary>
        /// NFileUpLoadExperience control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VIS_website.Documents.NFileUpLoad NFileUpLoadExperience;
    }
}
